version: "3.9" # optional since v1.27.0
services:
  web_api:
    image: web_api
    container_name: web_api_application
    ports:
      - "5000:80"
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql-server-2022
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A!VeryComplex123Password
