image: docker/compose:latest

services:
  - docker:dind

# Define the GitLab CI/CD stages
stages:
  - build

# Build stage
build_push_hub:
  stage: build
  script:
    - docker-compose --version
    - docker build --force-rm -t $DOCKER_USERNAME/web_api:latest .
    - docker build -f db/Dockerfile --force-rm -t $DOCKER_USERNAME/sql:latest ./db
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker run -d $DOCKER_USERNAME/sql  
    - docker run -d $DOCKER_USERNAME/web_api 
    - docker push $DOCKER_USERNAME/sql:latest
    - docker push $DOCKER_USERNAME/web_api:latest
