version: "3.9" # optional since v1.27.0
services:
  web_api:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: web
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - sql
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql
    ports:
      - "14345:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=A!VeryComplex123Password
